# Generated by Django 5.2.7 on 2026-01-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=10, unique=True)),
                ('station_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['station_name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('train_name', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField(default=100, help_text='Total seats available')),
                ('available_seats', models.IntegerField(default=100, help_text='Currently available seats')),
                ('total_coaches', models.IntegerField(default=10)),
                ('classes_available', models.CharField(help_text='e.g., AC,Non-AC,Sleeper', max_length=100)),
                ('off_day', models.CharField(blank=True, help_text="Days when train doesn't run (e.g., Sunday)", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'ordering': ['train_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(help_text='Default departure time')),
                ('arrival_time', models.TimeField(help_text='Default arrival time at final destination')),
                ('off_days', models.CharField(blank=True, help_text="Days when train doesn't run (e.g., Sunday,Monday)", max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='trains.train')),
            ],
            options={
                'verbose_name': 'Train Schedule',
                'verbose_name_plural': 'Train Schedules',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(help_text='Station sequence in route (1, 2, 3...)')),
                ('arrival_time', models.TimeField(blank=True, help_text='Arrival time at this station', null=True)),
                ('departure_time', models.TimeField(help_text='Departure time from this station')),
                ('distance_from_origin', models.DecimalField(decimal_places=2, default=0, help_text='Distance in KM from first station', max_digits=6)),
                ('day_offset', models.IntegerField(default=0, help_text='Days after journey start')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='trains.train')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['train', 'sequence_order'],
                'unique_together': {('train', 'sequence_order')},
            },
        ),
    ]
