# Generated by Django 5.2.7 on 2025-10-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=10, unique=True)),
                ('station_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['station_name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('train_name', models.CharField(max_length=100)),
                ('total_coaches', models.IntegerField(default=10)),
                ('classes_available', models.CharField(help_text='Comma separated: AC,Non-AC,Sleeper', max_length=100)),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'ordering': ['train_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='running', max_length=20)),
                ('delay_minutes', models.IntegerField(default=0, help_text='Delay in minutes')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
            ],
            options={
                'verbose_name': 'Train Schedule',
                'verbose_name_plural': 'Train Schedules',
                'ordering': ['-journey_date'],
                'unique_together': {('train', 'journey_date')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(help_text='Station sequence in route (1, 2, 3...)')),
                ('arrival_time', models.TimeField(blank=True, help_text='Arrival time at this station', null=True)),
                ('departure_time', models.TimeField(help_text='Departure time from this station')),
                ('distance_from_origin', models.DecimalField(decimal_places=2, default=0, help_text='Distance in KM', max_digits=6)),
                ('day_offset', models.IntegerField(default=0, help_text='Days after journey start (0=same day, 1=next day)')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='trains.train')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['train', 'sequence_order'],
                'unique_together': {('train', 'sequence_order')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_number', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('class_type', models.CharField(choices=[('AC', 'Air Conditioned'), ('Non-AC', 'Non Air Conditioned'), ('Sleeper', 'Sleeper')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('train_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='trains.trainschedule')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'unique_together': {('train_schedule', 'coach_number', 'seat_number')},
            },
        ),
    ]
