# Generated by Django 6.0.1 on 2026-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'Booked'), ('travelled', 'Travelled'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
